name: Notify Main Repo on Submodule Update

on:
  push:
    branches:
      - main # or the branch you want to monitor

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Main Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GAMENAME_REPO_TOKEN }}" \
          https://api.github.com/repos/owner/main-repo/actions/workflows/ota-reload-on-commit.yml/dispatches \
          -d '{"ref":"main"}'
